/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LocationRouteImport } from './routes/location'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StayRouteImport } from './routes/stay'
import { Route as StaysNearLakeMuhaziRouteImport } from './routes/stays-near-lake-muhazi'
import { Route as WeekendEscapesNearKigaliRouteImport } from './routes/weekend-escapes-near-kigali'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardCalendarRouteImport } from './routes/_authenticated/dashboard.calendar'
import { Route as AuthenticatedDashboardChannelsRouteImport } from './routes/_authenticated/dashboard.channels'
import { Route as AuthenticatedDashboardContentRouteImport } from './routes/_authenticated/dashboard.content'
import { Route as AuthenticatedDashboardEventsRouteImport } from './routes/_authenticated/dashboard.events'
import { Route as AuthenticatedDashboardGuestsRouteImport } from './routes/_authenticated/dashboard.guests'
import { Route as AuthenticatedDashboardInquiriesRouteImport } from './routes/_authenticated/dashboard.inquiries'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardPricingRouteImport } from './routes/_authenticated/dashboard.pricing'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as ApiPublicIcalChannelIdRouteImport } from './routes/api/public/ical.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StayRoute = StayRouteImport.update({
  id: '/stay',
  path: '/stay',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysNearLakeMuhaziRoute = StaysNearLakeMuhaziRouteImport.update({
  id: '/stays-near-lake-muhazi',
  path: '/stays-near-lake-muhazi',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendEscapesNearKigaliRoute =
  WeekendEscapesNearKigaliRouteImport.update({
    id: '/weekend-escapes-near-kigali',
    path: '/weekend-escapes-near-kigali',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarRoute =
  AuthenticatedDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChannelsRoute =
  AuthenticatedDashboardChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContentRoute =
  AuthenticatedDashboardContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEventsRoute =
  AuthenticatedDashboardEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGuestsRoute =
  AuthenticatedDashboardGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInquiriesRoute =
  AuthenticatedDashboardInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPricingRoute =
  AuthenticatedDashboardPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicIcalChannelIdRoute = ApiPublicIcalChannelIdRouteImport.update({
  id: '/api/public/ical/$channelId',
  path: '/api/public/ical/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stay': typeof StayRoute
  '/stays-near-lake-muhazi': typeof StaysNearLakeMuhaziRoute
  '/weekend-escapes-near-kigali': typeof WeekendEscapesNearKigaliRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/channels': typeof AuthenticatedDashboardChannelsRoute
  '/dashboard/content': typeof AuthenticatedDashboardContentRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/ical/$channelId': typeof ApiPublicIcalChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stay': typeof StayRoute
  '/stays-near-lake-muhazi': typeof StaysNearLakeMuhaziRoute
  '/weekend-escapes-near-kigali': typeof WeekendEscapesNearKigaliRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/channels': typeof AuthenticatedDashboardChannelsRoute
  '/dashboard/content': typeof AuthenticatedDashboardContentRoute
  '/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/ical/$channelId': typeof ApiPublicIcalChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stay': typeof StayRoute
  '/stays-near-lake-muhazi': typeof StaysNearLakeMuhaziRoute
  '/weekend-escapes-near-kigali': typeof WeekendEscapesNearKigaliRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/_authenticated/dashboard/channels': typeof AuthenticatedDashboardChannelsRoute
  '/_authenticated/dashboard/content': typeof AuthenticatedDashboardContentRoute
  '/_authenticated/dashboard/events': typeof AuthenticatedDashboardEventsRoute
  '/_authenticated/dashboard/guests': typeof AuthenticatedDashboardGuestsRoute
  '/_authenticated/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/pricing': typeof AuthenticatedDashboardPricingRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/ical/$channelId': typeof ApiPublicIcalChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/experiences'
    | '/gallery'
    | '/location'
    | '/sitemap.xml'
    | '/stay'
    | '/stays-near-lake-muhazi'
    | '/weekend-escapes-near-kigali'
    | '/dashboard'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/channels'
    | '/dashboard/content'
    | '/dashboard/events'
    | '/dashboard/guests'
    | '/dashboard/inquiries'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/ical/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/experiences'
    | '/gallery'
    | '/location'
    | '/sitemap.xml'
    | '/stay'
    | '/stays-near-lake-muhazi'
    | '/weekend-escapes-near-kigali'
    | '/dashboard/bookings'
    | '/dashboard/calendar'
    | '/dashboard/channels'
    | '/dashboard/content'
    | '/dashboard/events'
    | '/dashboard/guests'
    | '/dashboard/inquiries'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/ical/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/experiences'
    | '/gallery'
    | '/location'
    | '/sitemap.xml'
    | '/stay'
    | '/stays-near-lake-muhazi'
    | '/weekend-escapes-near-kigali'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/calendar'
    | '/_authenticated/dashboard/channels'
    | '/_authenticated/dashboard/content'
    | '/_authenticated/dashboard/events'
    | '/_authenticated/dashboard/guests'
    | '/_authenticated/dashboard/inquiries'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/pricing'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/api/public/ical/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StayRoute: typeof StayRoute
  StaysNearLakeMuhaziRoute: typeof StaysNearLakeMuhaziRoute
  WeekendEscapesNearKigaliRoute: typeof WeekendEscapesNearKigaliRoute
  ApiPublicIcalChannelIdRoute: typeof ApiPublicIcalChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stay': {
      id: '/stay'
      path: '/stay'
      fullPath: '/stay'
      preLoaderRoute: typeof StayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays-near-lake-muhazi': {
      id: '/stays-near-lake-muhazi'
      path: '/stays-near-lake-muhazi'
      fullPath: '/stays-near-lake-muhazi'
      preLoaderRoute: typeof StaysNearLakeMuhaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend-escapes-near-kigali': {
      id: '/weekend-escapes-near-kigali'
      path: '/weekend-escapes-near-kigali'
      fullPath: '/weekend-escapes-near-kigali'
      preLoaderRoute: typeof WeekendEscapesNearKigaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendar': {
      id: '/_authenticated/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/channels': {
      id: '/_authenticated/dashboard/channels'
      path: '/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof AuthenticatedDashboardChannelsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/content': {
      id: '/_authenticated/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof AuthenticatedDashboardContentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/events': {
      id: '/_authenticated/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof AuthenticatedDashboardEventsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/guests': {
      id: '/_authenticated/dashboard/guests'
      path: '/guests'
      fullPath: '/dashboard/guests'
      preLoaderRoute: typeof AuthenticatedDashboardGuestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inquiries': {
      id: '/_authenticated/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof AuthenticatedDashboardInquiriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pricing': {
      id: '/_authenticated/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof AuthenticatedDashboardPricingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/ical/$channelId': {
      id: '/api/public/ical/$channelId'
      path: '/api/public/ical/$channelId'
      fullPath: '/api/public/ical/$channelId'
      preLoaderRoute: typeof ApiPublicIcalChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardCalendarRoute: typeof AuthenticatedDashboardCalendarRoute
  AuthenticatedDashboardChannelsRoute: typeof AuthenticatedDashboardChannelsRoute
  AuthenticatedDashboardContentRoute: typeof AuthenticatedDashboardContentRoute
  AuthenticatedDashboardEventsRoute: typeof AuthenticatedDashboardEventsRoute
  AuthenticatedDashboardGuestsRoute: typeof AuthenticatedDashboardGuestsRoute
  AuthenticatedDashboardInquiriesRoute: typeof AuthenticatedDashboardInquiriesRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardPricingRoute: typeof AuthenticatedDashboardPricingRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardCalendarRoute: AuthenticatedDashboardCalendarRoute,
    AuthenticatedDashboardChannelsRoute: AuthenticatedDashboardChannelsRoute,
    AuthenticatedDashboardContentRoute: AuthenticatedDashboardContentRoute,
    AuthenticatedDashboardEventsRoute: AuthenticatedDashboardEventsRoute,
    AuthenticatedDashboardGuestsRoute: AuthenticatedDashboardGuestsRoute,
    AuthenticatedDashboardInquiriesRoute: AuthenticatedDashboardInquiriesRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardPricingRoute: AuthenticatedDashboardPricingRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StayRoute: StayRoute,
  StaysNearLakeMuhaziRoute: StaysNearLakeMuhaziRoute,
  WeekendEscapesNearKigaliRoute: WeekendEscapesNearKigaliRoute,
  ApiPublicIcalChannelIdRoute: ApiPublicIcalChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
